name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable and Configure RDP
        run: |
          # Enable Remote Desktop and disable Network Level Authentication
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                           -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                           -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                           -Name "SecurityLayer" -Value 0 -Force

          # Allow RDP traffic through firewall
          netsh advfirewall firewall delete rule name="RDP-Allow" > $null 2>&1
          netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure Password
        run: |
          Add-Type -AssemblyName System.Security

          # Define character sets
          $upper = [char[]](65..90)        # A-Z
          $lower = [char[]](97..122)       # a-z
          $numbers = [char[]](48..57)      # 0-9
          $symbols = [char[]]"!@#$%^&*()-_=+[]{};:,.<>/?"
          $charPool = $upper + $lower + $numbers + $symbols

          # Generate a 16-character random password
          $password = -join ((1..16) | ForEach-Object { $charPool | Get-Random })

          # Create user safely
          $username = "RDPUser"
          net user $username $password /add /Y
          if ($LASTEXITCODE -eq 0) {
            net localgroup administrators $username /add
          } else {
            Write-Host "❌ Failed to create user."
            exit 1
          }

          Write-Host "====================================="
          Write-Host "✅ RDP User Created Successfully!"
          Write-Host "Username: $username"
          Write-Host "Password: $password"
          Write-Host "====================================="

      - name: Display Connection Info
        run: |
          $ip = (Invoke-RestMethod -Uri "https://api.ipify.org?format=json").ip
          Write-Host "====================================="
          Write-Host "🌐 Public IP: $ip"
          Write-Host "🖥️  Connect via RDP using:"
          Write-Host "   Address: $ip"
          Write-Host "   Username: RDPUser"
          Write-Host "====================================="
